In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
processed_data_path=os.path.join(os.path.pardir,'data','processed')
write_train_path=os.path.join(processed_data_path,'train.csv')
write_test_path=os.path.join(processed_data_path,'test.csv')

In [3]:
train_df=pd.read_csv(write_train_path,index_col='PassengerId')
test_df=pd.read_csv(write_test_path,index_col='PassengerId')

In [4]:
X=train_df.loc[:,'Family_Size':].as_matrix().astype('float');
y=train_df['Survived'].ravel()

C:\ProgramData\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [5]:
X.shape

(891L, 41L)

In [6]:
y.shape

(891L,)

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [8]:
print X_train.shape,y_train.shape
print X_test.shape,y_test.shape

(712L, 41L) (712L,)
(179L, 41L) (179L,)


In [9]:
print np.mean(y_train)
print np.mean(y_test)

0.38342696629213485
0.3854748603351955


In [10]:
%%HTML
<h2>IMBALANCE CLASS PROBLEM (to be studied later)</h2>

In [11]:
import sklearn

In [12]:
sklearn.__version__

'0.19.1'

In [13]:
from sklearn.dummy import DummyClassifier

In [14]:
model_dummy=DummyClassifier(strategy='most_frequent',random_state=0)

In [15]:
model_dummy.fit(X_train,y_train)

DummyClassifier(constant=None, random_state=0, strategy='most_frequent')

In [16]:
model_dummy.score(X_test,y_test)

0.6145251396648045

In [17]:
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score

In [18]:
accuracy_score(y_test,model_dummy.predict(X_test))

0.6145251396648045

In [19]:
confusion_matrix(y_test,model_dummy.predict(X_test))

array([[110,   0],
       [ 69,   0]], dtype=int64)

In [20]:
precision_score(y_test,model_dummy.predict(X_test))

C:\ProgramData\Anaconda2\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


0.0

In [21]:
recall_score(y_test,model_dummy.predict(X_test))

0.0

In [22]:
%%HTML
<h1> FIRST KAGGLE SUBMISSION</h1>

In [23]:
test_X=test_df.loc[:,'Family_Size':].as_matrix().astype('float')
predictions=model_dummy.predict(test_X)

df_submission=pd.DataFrame({'PassengerId':test_df.index,'Survived':predictions})
df_submission.head()

C:\ProgramData\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         0

In [24]:
submission_data_path=os.path.join(os.path.pardir,'data','external')
submission_file_path=os.path.join(submission_data_path,'01_dummy.csv')

In [25]:
#df_submission.to_csv(submission_file_path,index=False)

In [26]:
def get_submission_file(model,filename):
    test_X=test_df.loc[:,'Family_Size':].as_matrix().astype('float')    
    predictions=model.predict(test_X)
    df_submission=pd.DataFrame({'PassengerId':test_df.index,'Survived':predictions})
    submission_data_path=os.path.join(os.path.pardir,'data','external')
    submission_file_path=os.path.join(submission_data_path,filename)
    df_submission.to_csv(submission_file_path,index=False)


In [27]:
get_submission_file(model_dummy,'03_dummy.csv')

C:\ProgramData\Anaconda2\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


In [28]:
%%HTML
<h2>LOGISTIC REGRESSION MODEL</h2>

In [29]:
from sklearn.linear_model import LogisticRegression

In [30]:
model_lr=LogisticRegression(random_state=0)

In [31]:
model_lr.fit(X_train,y_train)
model_lr.score(X_test,y_test)

0.8156424581005587

In [32]:
accuracy_score(y_test,model_lr.predict(X_test))

0.8156424581005587

In [33]:
precision_score(y_test,model_lr.predict(X_test))

0.7571428571428571

In [34]:
recall_score(y_test,model_lr.predict(X_test))

0.7681159420289855

In [35]:
confusion_matrix(y_test,model_lr.predict(X_test))

array([[93, 17],
       [16, 53]], dtype=int64)

In [36]:

get_submission_file(model_lr,'01_lr.csv')

C:\ProgramData\Anaconda2\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


In [37]:
test_X

array([[1., 0., 1., ..., 0., 1., 0.],
       [2., 0., 0., ..., 1., 1., 0.],
       [1., 0., 1., ..., 0., 1., 0.],
       ...,
       [1., 0., 1., ..., 1., 1., 0.],
       [1., 0., 1., ..., 1., 1., 0.],
       [3., 0., 1., ..., 0., 0., 1.]])

In [38]:
np.where(np.isnan(test_X))


(array([], dtype=int64), array([], dtype=int64))

In [39]:
test_X[1]

array([2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 1., 0.])

In [40]:
test_df[test_df.Age==60.5]

Survived   Age  Fare  Family_Size  isMother  isMale  Deck_A  \
PassengerId                                                                
1044             -888  60.5   NaN            1         0       1       0   

             Deck_B  Deck_C  Deck_D       ...        Title_the countess  \
PassengerId                               ...                             
1044              0       0       0       ...                         0   

             Fare_Bin_very_low  Fare_Bin_low  Fare_Bin_high  \
PassengerId                                                   
1044                         0             0              0   

             Fare_Bin_very_high  Embarked_C  Embarked_Q  Embarked_S  \
PassengerId                                                           
1044                          0           0           0           1   

             AgeState_Adult  AgeState_Child  
PassengerId                                  
1044                      1               0  

[1 rows x 44 columns]

In [41]:
%%HTML
<h2>MODEL TUNING</h2>
<h3 style="color:red">UNDERFITTING & OVERFITTING</h3>
<h3 style="color:green">REGULARIZATION</h3>
<h3 style="color:blue">HYPERPARAMTER TUNING</h3>
<h3 style="color:red">CROSS VALIDATION</h3>

In [42]:
%%HTML
<h2>FEATURE ENGINEERING</h2>
<h3 style="color:red">1. FEATURE NORMALIZATION</h3>
<HR>
<h2>MODEL PERSISTENCE</h2>
<HR>
<h2>API</h2>
<HR>

In [43]:
%%HTML
<h2>TOOLS</h2>
<h3 style="color:red">1. numpy</h3>
<h3 style="color:blue">2. pandas</h3>
<h3 style="color:violet">3. scikit-learn</h3>
<h3 style="color:orange">4. pickle</h3>
<h3 style="color:green">5. flask</h3>


In [45]:
# AVOID UNDERFITTING ANF OVERFITTING MODELS
# WAYS TO AVOID OVERFITTING
# 1. REGULARIZATION
# penalty,c <- regularization hyperparameters
# penalty-> l1,l2(default)

In [47]:
# Hyper-parameter Optimization 
# GRIDSEARCH

In [48]:
# CROSS-VALIDATION
# K-FOLD CROSS VALIDATION
# K=3 , 3 Fold

In [49]:
# GRIDSEARCH CV - Hyperparamter Optimization


In [50]:
from sklearn.model_selection import GridSearchCV

In [83]:
paramters={'C':[0.5,1.0,10.0,25.0,50.0,100.0,1000.0],'penalty':['l1','l2']}
clf=GridSearchCV(model_lr,paramters,cv=15)

In [84]:
clf.fit(X_train,y_train)

GridSearchCV(cv=15, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'penalty': ['l1', 'l2'], 'C': [0.5, 1.0, 10.0, 25.0, 50.0, 100.0, 1000.0]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [85]:
clf.best_params_

{'C': 1.0, 'penalty': 'l1'}

In [86]:
clf.best_score_


0.8314606741573034

In [87]:
clf.score(X_test,y_test)

0.8156424581005587

In [88]:
get_submission_file(clf,'04_clf.csv')

C:\ProgramData\Anaconda2\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


In [89]:
#FEATURE NORMALIZATION AND STANDARDIZATION


In [90]:
# SCALE 1 ->  0 to 1
# SCALE 2 -> -1 to 1


In [91]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler

In [98]:
# feature normalization
scaler=MinMaxScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.fit_transform(X_test)

In [99]:
# standardization
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.fit_transform(X_test)

In [101]:
model_lr=LogisticRegression(random_state=0)

In [110]:
paramters={'C':[1.0,10.0,25.0,50.0,100.0,1000.0],'penalty':['l1','l2']}
clf=GridSearchCV(model_lr,paramters,cv=3)
clf.fit(X_train,y_train)

GridSearchCV(cv=3, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'penalty': ['l1', 'l2'], 'C': [1.0, 10.0, 25.0, 50.0, 100.0, 1000.0]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [111]:
clf.best_score_

0.8258426966292135

In [112]:
clf.best_params_

{'C': 1.0, 'penalty': 'l2'}

In [113]:
clf.score(X_test_scaled,y_test)

0.7877094972067039

In [114]:
#MODEL PERSISTENCE

In [115]:
%%HTML
<h1> MODEL PERSISTENCE</h1>

In [116]:
import pickle

In [118]:
model_file_path=os.path.join(os.path.pardir,'models','lr_model.pkl')
scaler_file_path=os.path.join(os.path.pardir,'models','lr_scaler.pkl')

model_file_pickle=open(model_file_path,'wb')
scaler_file_pickle=open(scaler_file_path,'wb')

pickle.dump(clf,model_file_pickle)
pickle.dump(scaler,scaler_file_pickle)

model_file_pickle.close()
scaler_file_pickle.close()